import { useState, useEffect } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { supabase } from '@/lib/supabase'
import { useAuthStore } from '@/store/authStore'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/FormFields'
import { SEOHead } from '@/components/seo/SEOHead'
import { ShieldAlert, ArrowLeft, KeyRound, LogOut } from 'lucide-react'

export function MfaChallengePage() {
  const navigate = useNavigate()
  const location = useLocation()
  const user = useAuthStore((s) => s.user)
  const setMfaEnrolled = useAuthStore((s) => s.setMfaEnrolled)

  const [factorId, setFactorId] = useState<string | null>(null)
  const [challengeId, setChallengeId] = useState<string | null>(null)
  const [code, setCode] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [isInitializing, setIsInitializing] = useState(true)

  const returnUrl = (location.state as any)?.from?.pathname || '/admin'

  useEffect(() => {
    if (!user) {
      navigate('/auth/login', { replace: true })
      return
    }

    async function initChallenge() {
      try {
        setIsInitializing(true)
        setError(null)

        // 1. List factors
        const { data: factorsData, error: factorsError } = await supabase.auth.mfa.listFactors()
        if (factorsError) throw factorsError

        const totpFactor = factorsData.totp.find((f) => f.status === 'verified')
        if (!totpFactor) {
          // No verified factor enrolled, guide user to setup
          setMfaEnrolled(false)
          navigate('/auth/mfa-setup', { replace: true })
          return
        }

        setFactorId(totpFactor.id)
        setMfaEnrolled(true)

        // 2. Create challenge
        const { data: cData, error: cError } = await supabase.auth.mfa.challenge({
          factorId: totpFactor.id,
        })
        if (cError) throw cError

        setChallengeId(cData.id)
      } catch (err: any) {
        setError(err.message || 'Failed to initialize two-factor verification')
      } finally {
        setIsInitializing(false)
      }
    }

    initChallenge()
  }, [user, navigate, setMfaEnrolled])

  const handleVerify = async (e?: React.FormEvent) => {
    if (e) e.preventDefault()
    if (code.length !== 6 || !factorId || !challengeId) return

    setIsLoading(true)
    setError(null)

    try {
      const { error: verifyError } = await supabase.auth.mfa.verify({
        factorId,
        challengeId,
        code,
      })

      if (verifyError) throw verifyError

      // Successful verification
      navigate(returnUrl, { replace: true })
    } catch (err: any) {
      setError(err.message || 'Invalid verification code. Please try again.')
      setCode('')
    } finally {
      setIsLoading(false)
    }
  }

  const handleSignOut = async () => {
    await supabase.auth.signOut()
    navigate('/auth/login', { replace: true })
  }

  return (
    <>
      <SEOHead title="Two-Factor Challenge — AK QIMAASH" description="Enter your 2FA authentication code to continue." />
      <div className="min-h-[80vh] flex items-center justify-center px-4 py-12">
        <div className="w-full max-w-[420px]">
          {/* Card */}
          <div className="bg-surface-raised border border-border rounded-xl p-8 shadow-card">
            {/* Header */}
            <div className="text-center mb-6">
              <div className="mx-auto w-14 h-14 rounded-2xl bg-amber-500/10 flex items-center justify-center mb-4">
                <KeyRound className="w-7 h-7 text-amber-600" />
              </div>
              <h1 className="text-2xl font-semibold text-text-primary tracking-tight">
                Two-Factor Challenge
              </h1>
              <p className="text-sm text-text-muted mt-2">
                Enter the 6-digit security code generated by your authenticator app.
              </p>
            </div>

            {error && (
              <div className="mb-6 p-4 rounded-lg bg-error-light border border-error/20 flex items-start gap-3">
                <ShieldAlert className="w-5 h-5 text-error shrink-0 mt-0.5" />
                <p className="text-sm text-error leading-snug">{error}</p>
              </div>
            )}

            {isInitializing ? (
              <div className="py-8 flex flex-col items-center justify-center gap-3">
                <div className="h-6 w-6 border-2 border-brand-black border-t-transparent rounded-full animate-spin" />
                <p className="text-xs text-text-muted">Connecting to authenticator service…</p>
              </div>
            ) : (
              <form onSubmit={handleVerify} className="space-y-6">
                <div>
                  <label htmlFor="mfa-code" className="block text-xs font-medium uppercase tracking-caps text-text-muted mb-2 text-center">
                    6-Digit Security Code
                  </label>
                  <Input
                    id="mfa-code"
                    type="text"
                    inputMode="numeric"
                    autoComplete="one-time-code"
                    maxLength={6}
                    placeholder="000000"
                    value={code}
                    onChange={(e) => {
                      const val = e.target.value.replace(/\D/g, '').slice(0, 6)
                      setCode(val)
                      if (val.length === 6 && factorId && challengeId) {
                        // Auto-submit when 6 digits are typed
                        setTimeout(() => {
                          const submitBtn = document.getElementById('verify-mfa-btn')
                          submitBtn?.click()
                        }, 50)
                      }
                    }}
                    autoFocus
                    className="text-center font-mono text-2xl tracking-[0.5em] py-3 placeholder:tracking-normal placeholder:font-sans placeholder:text-sm"
                  />
                </div>

                <Button
                  id="verify-mfa-btn"
                  type="submit"
                  variant="primary"
                  size="lg"
                  className="w-full"
                  isLoading={isLoading}
                  disabled={code.length !== 6 || isLoading}
                >
                  Verify and Continue
                </Button>
              </form>
            )}

            <div className="mt-8 pt-6 border-t border-border flex items-center justify-between text-xs text-text-muted">
              <button
                type="button"
                onClick={() => navigate('/auth/mfa-setup')}
                className="hover:text-text-primary transition-colors flex items-center gap-1"
              >
                Need to re-enroll?
              </button>

              <button
                type="button"
                onClick={handleSignOut}
                className="hover:text-error transition-colors flex items-center gap-1.5"
              >
                <LogOut className="w-3.5 h-3.5" />
                Sign out
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
